name: Automatic Rebase

on: [pull_request_target]

permissions:
  contents: read

jobs:
  _:
    uses: ljharb/actions/.github/workflows/rebase.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

